version: '3.4'

services:
  server:
    image: gorss:alpha
    build: .
    ports:
      - 8000:8000
    volumes: 
      - .:/usr/src/app
    links: 
      - postgresdb

  postgresdb:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=hmuir

volumes: 
  data:
